server:
  port: 8080
spring:
  application:
    name: search-api
  data:
    mongodb:
      database: assignment
      host: localhost
      port: 27017
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  main:
    allow-bean-definition-overriding: true
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /